diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
core.editor="C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
core.autocrlf=true
user.name=dothebest9
user.email=smrmtjsrn11@naver.com
difftool.sourcetree.cmd='' 
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=false
mergetool.sourcetree.keepbackup=false
